# Generated by Django 4.0 on 2021-12-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='hits',
            field=models.IntegerField(default=0, verbose_name='瀏覽次數'),
        ),
    ]
